# Generated by Django 4.1.7 on 2023-05-07 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_publish_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(verbose_name=datetime.datetime(2023, 5, 7, 15, 12, 56, 315606, tzinfo=datetime.timezone.utc)),
        ),
    ]
